server:
    port: 8091
spring:
  datasource:
    url: jdbc:h2:mem:msstudent
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
